---
- name: Install Apache web server
  apt: pkg=apache2 state=installed
  register: install_apache

- name: Copy Apache landing page
  when: install_apache | success
  template:
    src: landingpage.j2
    dest: /var/www/html/index.html
