---
# Playbook to bootstrap configuration for machines in WPI secnet.
# TODO
# + install zsh
# + install oh-my-zsh
# + setup hostname
# + alias
- hosts: gateway
  vars:
    - username: cs4516
    - host_no: host2
  become: yes
  roles:
    - common
    - gen-alias
    - openvswitch

- hosts: webserver
  vars:
    - username: cs4516
    - host_no: host3
    - servername: "WEB SERVER"
  become: yes
  roles:
    - apache

- hosts: honeypot
  vars:
    - username: cs4516
    - host_no: host4
    - servername: "HONEYPOT SERVER"
  become: yes
  roles:
    - apache

- hosts: openflow_controller
  roles:
    - floodlight

# - hosts: dns,honeypot,openflow_controller
#   roles:
#     - apache
#     - bind9
