---
# Playbook to bootstrap configuration for machines in WPI secnet.
# TODO
# + setup hostname

- hosts: client
  vars:
    - username: cs4516
    - host_no: host1
    - controller_ip: 10.45.17.4
  become: yes
  roles:
    - common
    - openvswitch
    - dns-client-conf

- hosts: gateway
  vars:
    - username: cs4516
    - controller_ip: 10.45.17.4
  become: yes
  roles:
    - common
    - openvswitch
  tags:
    - debug

- hosts: webserver
  vars:
    - username: cs4516
    - host_no: host3
    - servername: "WEB SERVER"
  become: yes
  roles:
    - apache
    - gen-alias

- hosts: dns
  vars:
    - username: cs4516
    - host_no: host2
  become: yes
  roles:
    - bind9

#- hosts: openflow_controller
#  roles:
#    - floodlight
