---
- name: Copy interfaces file to VM
  copy:
    src: interfaces.{{ host_no }}
    dest: /etc/network/interfaces
  register: cpinterfaces

# TODO fail to run
# - name: Restart networking service
#   when: cpinterfaces|success
#   shell: sudo /etc/init.d/networking restart
#   become: yes
#   become_user: "{{ username }}"
#   ignore_errors: yes
