---
- name: Create IP alises {128..254}
  become_user: root
  become: yes
  script: create-aliases.sh
  register: cpinterfaces
  ignore_errors: yes

# TODO fail to run
- name: Restart networking service
  when: cpinterfaces|success
  service: name=networking state=restarted enabled=yes
  ignore_errors: yes
